sudo: false
language: scala

jdk:
  - openjdk11

before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

scala_version_213: &scala_version_213 "2.13.1"

jobs:
  include:
    # stage="test" if no stage is specified
    - name: test 2.13
      scala: *scala_version_213
      script: sbt ++$TRAVIS_SCALA_VERSION test
    # run ci-release only if previous stages passed
    - stage: release
      name: release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/.cache
    - $HOME/.sbt