addSbtPlugin("org.typelevel" % "sbt-typelevel"         % "0.7.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.7.4")
addSbtPlugin("org.typelevel" % "sbt-fs2-grpc"          % "2.7.20")
addSbtPlugin("io.spray"      % "sbt-revolver"          % "0.10.0")
addSbtPlugin("com.eed3si9n"  % "sbt-buildinfo"         % "0.12.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc"              % "2.6.1")
