addSbtPlugin("ch.epfl.lamp"          % "sbt-dotty"      % "0.4.2")
addSbtPlugin("com.codecommit"        % "sbt-spiewak"    % "0.15.2")
addSbtPlugin("com.geirsson"          % "sbt-ci-release" % "1.5.3")
addSbtPlugin("org.lyranthe.fs2-grpc" % "sbt-java-gen"   % "0.7.3")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("io.spray"              % "sbt-revolver"   % "0.9.1")
addSbtPlugin("com.eed3si9n"          % "sbt-buildinfo"  % "0.10.0")
