addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.4.16")
addSbtPlugin("org.typelevel" % "sbt-fs2-grpc"  % "2.5.1")
addSbtPlugin("io.spray"      % "sbt-revolver"  % "0.9.1")
addSbtPlugin("com.eed3si9n"  % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc"      % "2.3.6")
