version: '3.8'

x-common-variables: &common-variables
  EVENTSTORE_CLUSTER_SIZE: "3"

services:

  es1:
    image: eventstore/eventstore:20.10.0-bionic
    env_file:
      - shared.env
    environment:
      <<: *common-variables
      EVENTSTORE_GOSSIP_SEED: "${SEC_ESC_2_IP}:2113,${SEC_ESC_3_IP}:2113"
      EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS: "2114"
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - 2114:2113
    networks:
      es_cluster_network:
        ipv4_address: "$SEC_ESC_1_IP"
    depends_on:
      - cert-gen

  es2:
    image: eventstore/eventstore:20.10.0-bionic
    env_file:
      - shared.env
    environment:
      <<: *common-variables
      EVENTSTORE_GOSSIP_SEED: "${SEC_ESC_1_IP}:2113,${SEC_ESC_3_IP}:2113"
      EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS: "2115"
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - 2115:2113
    networks:
      es_cluster_network:
        ipv4_address: "$SEC_ESC_2_IP"
    depends_on:
      - cert-gen

  es3:
    image: eventstore/eventstore:20.10.0-bionic
    env_file:
      - shared.env
    environment:
      <<: *common-variables
      EVENTSTORE_GOSSIP_SEED: "${SEC_ESC_1_IP}:2113,${SEC_ESC_2_IP}:2113"
      EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS: "2116"
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - 2116:2113
    networks:
      es_cluster_network:
        ipv4_address: "$SEC_ESC_3_IP"
    depends_on:
      - cert-gen

networks:
  es_cluster_network:
    name: es-cluster-net
    ipam:
      driver: default
      config:
        - subnet: "$SEC_ESC_SUBNET"