x-common-variables: &common-variables
  KURRENTDB_CLUSTER_SIZE: "3"

services:

  kdb1:
    image: "$KDB_IMAGE"
    env_file:
      - ./shared.env
    environment:
      <<: *common-variables
      KURRENTDB_GOSSIP_SEED: "${SEC_CL_2_IP}:2113,${SEC_CL_3_IP}:2113"
      KURRENTDB_ADVERTISE_NODE_PORT_TO_CLIENT_AS: "2114"
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - "2114:2113"
    networks:
      kdb_cluster_network:
        ipv4_address: "$SEC_CL_1_IP"
    depends_on:
      - cert-gen
    restart: on-failure:10

  kdb2:
    image: "$KDB_IMAGE"
    env_file:
      - ./shared.env
    environment:
      <<: *common-variables
      KURRENTDB_GOSSIP_SEED: "${SEC_CL_1_IP}:2113,${SEC_CL_3_IP}:2113"
      KURRENTDB_ADVERTISE_NODE_PORT_TO_CLIENT_AS: "2115"
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - "2115:2113"
    networks:
      kdb_cluster_network:
        ipv4_address: "$SEC_CL_2_IP"
    depends_on:
      - cert-gen
    restart: on-failure:10

  kdb3:
    image: "$KDB_IMAGE"
    env_file:
      - ./shared.env
    environment:
      <<: *common-variables
      KURRENTDB_GOSSIP_SEED: "${SEC_CL_1_IP}:2113,${SEC_CL_2_IP}:2113"
      KURRENTDB_ADVERTISE_NODE_PORT_TO_CLIENT_AS: "2116"
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - "2116:2113"
    networks:
      kdb_cluster_network:
        ipv4_address: "$SEC_CL_3_IP"
    depends_on:
      - cert-gen
    restart: on-failure:10

networks:
  kdb_cluster_network:
    name: kdb-cluster-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "$SEC_CL_SUBNET"