version: '3.8'
services:

  es:
    image: quay.io/ahjohannessen/esdb:latest
    env_file:
      - ./shared.env
    environment:
      - EVENTSTORE_MEM_DB=True
      - EVENTSTORE_GOSSIP_ON_SINGLE_NODE=True
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - 2113:2113
    networks:
      es_single_network:
        ipv4_address: "$SEC_ESS_IP"
    depends_on:
      - cert-gen

networks:
  es_single_network:
    name: es-single-net
    ipam:
      driver: default
      config:
        - subnet: "$SEC_ESS_SUBNET"
