
services:

  es:
    image: "$KURRENTDB_IMAGE"
    env_file:
      - ./shared.env
    environment:
      - KURRENTDB_MEM_DB=True
      - KURRENTDB_START_STANDARD_PROJECTIONS=True
    volumes:
      - "$SEC_GENCERT_CERTS_PATH:/certs"
    ports:
      - 2113:2113
    networks:
      kdb_single_network:
        ipv4_address: "$SEC_SN_IP"
    depends_on:
      - cert-gen
    restart: on-failure:10

networks:
  kdb_single_network:
    name: kdb-single-net
    ipam:
      driver: default
      config:
        - subnet: "$SEC_SN_SUBNET"
