name: CI

on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    services:
      certs:
        image: quay.io/ahjohannessen/es-gencert-cli:1.0.1
        options: -v /github/workspace:/certs:rw --entrypoint "es-gencert-cli create-ca -out /certs"
      echo:
        image: busybox
        options: -v /github/workspace:/certs --entrypoint "ls -lR /certs"
      eventstore:
        image: quay.io/ahjohannessen/es-v6:latest
        env:
          EVENTSTORE_MEM_DB: True
          EVENTSTORE_INSECURE: True
          EVENTSTORE_DISCOVER_VIA_DNS: False
          EVENTSTORE_GOSSIP_ON_SINGLE_NODE: True
          EVENTSTORE_START_STANDARD_PROJECTIONS: True
        ports:
          - 1113:1113
          - 2113:2113

    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v7
    - name: run tests
      run: sbt "core/test" "core/it:test"

  publish:
    needs: test
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
      - uses: olafurpg/setup-gpg@v2

      - name: publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
