name: Continious Integration
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v2

    - name: Compile & Test
      run: sbt "core/test:compile" "core/test"