name: CI

on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Generate certificates
      run: misc/gencert.sh

    - name: Start Eventstore
      run: docker-compose -f misc/single-node.ci.yml up -d

    - uses: olafurpg/setup-scala@v7

    - name: Run tests
      run: sbt "core/test" "core/it:test"

    - name: Stop Eventstore
      run: docker-compose -f misc/single-node.ci.yml down
      if: always()

  publish:
    needs: test
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
      - uses: olafurpg/setup-gpg@v2

      - name: publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
