name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 206892
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          # used for authoring updates:
          github-token: ${{ steps.generate-token.outputs.token }}
          author-email: 123456+scala-steward-ahjohannessen[bot]@users.noreply.github.com
          author-name: scala-steward-ahjohannessen[bot]
          # used for listing repositories (optional, can be a different app):
          github-app-id: 206892
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
